# ?????? ?? URL
# jdbc:mysql://localhost:3306/drum: ?????? ?? ??? ??, ?????? ??
# serverTimezone=UTC: MySQL ???? ?? ???? UTC? ??
# characterEncoding=UTF-8: ?????? ???? ???? ?? ???? UTF-8? ??
spring:
  datasource:
#    url: jdbc:mysql://j9b107.p.ssafy.io:3500/drum?serverTimezone=UTC&characterEncoding=UTF-8
    url: jdbc:mysql://localhost:3306/drum?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: root
#    password: q1w2e3r4
    driver-class-name: com.mysql.cj.jdbc.Driver
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 구글 클라이언트 ID
            client-secret: 구글 클라이언트 Secret
            scope: profile, email

          kakao:
            client-id: e828c60d2aa66198c12dab645b40f9e6
            client-secret: u0ZpXoXzBFtxOkFlEIV2JogwxjyA0gLu
            redirect-uri: http://localhost:8000/login/oauth2/code/kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image
            client-name: Kakao

        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  profiles:
    include: oauth

# spring.jpa.show-sql: JPA? ???? SQL ??? ??? ???? ??? ??
# spring.jpa.hibernate.ddl-auto: Hibernate? DDL (??? ?? ??) ?? ?? ??? ??
# "none"?? ???? Hibernate? DDL ????? ???? ???? ??

# spring.jpa.properties.hibernate.format_sql: SQL ??? ??? ? SQL ?? ?? ?? ????? ??? ??
# true? ???? SQL ??? ?? ?? ???? ??
  jpa:
    show-sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

cloud:
  aws:
    s3:
      bucket: drumcomestrue
    region:
      static: ap-northeast-2 #Asia Pacific -> seoul
    stack:
      auto: false
    credentials:
      access-key: AKIAUEUEPWDIUDY33S2W
      secret-key: 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
servlet:
  multipart:
    enabled: true
    max-file-size: 20MB
    max-request-size: 20MB

server:
  port: 8000
  ssl:
        key-store: classpath:key.p12
        key-store-password: sslmaster
        key-store-type: PKCS12
jwt:
  secretKey: dasdasf234fuhvertsv34789yhi3sfgg
  access:
    expiration: 32460
    header: Authorization
  refresh:
    expiration: 1209600000
    header: Authorization-refresh
# 3600000
